source "http://rubygems.org"

gem 'exceptioner', :path => File.expand_path('../..')

# Specify your gem's dependencies in exceptioner-jabber.gemspec
gemspec

eval File.read(File.join(File.dirname(__FILE__), '../../development_dependencies.rb'))

