source "http://rubygems.org"


gem 'exceptioner-core', :path => File.expand_path('../../exceptioner-core')

# Specify your gem's dependencies in exceptioner-mail.gemspec
gemspec

eval File.read(File.join(File.dirname(__FILE__), '../../development_dependencies.rb'))

