require 'rake/testtask'
require 'bundler/gem_helper'
Bundler::GemHelper.install_tasks

ENV["RAILS_ENV"] ||= "test"

task :default => :test

desc 'Run Exceptioner-irc unit tests.'
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end
